const data = [
    {
      id: "1",
      title: 'An experimental evaluation of test driven development vs. test-last development with industry professionals',
      authors: "Munir, H., Wnuk, K., Petersen, K., Moayyed, M.",
      source: "EASE",
      pubyear: "2014",
      doi: "https://doi.org/10.1145/2601248.2601267",
      claim: "code quality improvement",
      evidence: "strong support",
    },
    {
      _id: "2",
      title: 'An experimental evaluation of test driven development vs. test-last development with industry professionals',
      authors: "Munir, H., Wnuk, K., Petersen, K., Moayyed, M.",
      source: "EASE",
      pubyear: "2014",
      doi: "https://doi.org/10.1145/2601248.2601267",
      claim: "product quality improvement",
      evidence: "weak support",
    },
    {
      _id: "3",
      title: 'Realizing quality improvement through test driven development: results and experiences of four industrial teams',
      authors: "Nagappan, N., Maximilien, E. M., Bhat, T., Williams, L.",
      source: " Empirical Software Engineering, 13(3), 289–302",
      pubyear: "2008",
      doi: "https://doi.org/10.1007/s10664-008-9062-z",
      claim: "product quality improvement",
      evidence: "weak support",
    },
    {
      _id: "4",
      title: "Does Test-Driven Development Really Improve Software Design Quality?",
      authors: "Janzen, D. S.",
      source: "Software, IEEE, 25(2) 77-84",
      pubyear: "2008",
      doi: "",
      claim: "code quality improvement",
      evidence: "strong support",
    },
    {
      _id: "5",
      title: "Comparative Case Study on the Impact of Test-Driven Development on Program Design and Test Coverage",
      authors: "Siniaalto, M., Abrahamsson, P.",
      source: "ArXiv.Org, cs.SE, arXiv:1711.05082-284",
      pubyear: "2017",
      doi: "",
      claim: "code quality improvement",
      evidence: "weak against",
    },
    {
      _id: "6",
      title: "Causal Factors, Benefits and Challenges of Test-Driven Development: Practitioner Perceptions",
      authors: "Buchan, Ji., Li, L. & MacDonell, S. G",
      source: "18TH ASIA PACIFIC SOFTWARE ENGINEERING CONFERENCE 2012",
      pubyear: "2012",
      doi: "https://doi.org/10.1109/apsec.2011.44",
      claim: "team satisfaction improvement",
      evidence: "weak support",
    },
    {
      _id: "7",
      title: "Causal Factors, Benefits and Challenges of Test-Driven Development: Practitioner Perceptions",
      authors: "Buchan, Ji., Li, L. & MacDonell, S. G",
      source: "18TH ASIA PACIFIC SOFTWARE ENGINEERING CONFERENCE 2012",
      pubyear: "2012",
      doi: "https://doi.org/10.1109/apsec.2011.44",
      claim: "product quality improvement",
      evidence: "weak against",
    },
    {
      _id: "8",
      title: "Driving Software Quality: How Test-Driven Development Impacts Software Quality.",
      authors: "Crispin, L",
      source: "IEEE Software, 23(6), 70–71.",
      pubyear: "2006",
      doi: "https://doi.org/10.1109/ms.2006.157",
      claim: "code quality improvement",
      evidence: "strong against",
    },
    {
      _id: "9",
      title: "On the effectiveness of unit tests in test-driven development.",
      authors: "Kuhrmann, M., O’Connor, R. V., Houston, D., Tosun, A., Ahmed, M., Turhan, B. & Juristo, N.",
      source: "ICSSP, 113–122",
      pubyear: "2018",
      doi: "https://doi.org/10.1145/3202710.3203153",
      claim: "product quality improvement",
      evidence: "",
    },
    {
      _id: "10",
      title: "On the effectiveness of unit tests in test-driven development.",
      authors: "Kuhrmann, M., O’Connor, R. V., Houston, D., Tosun, A., Ahmed, M., Turhan, B. & Juristo, N.",
      source: "ICSSP, 113–122",
      pubyear: "2018",
      doi: "https://doi.org/10.1145/3202710.3203153",
      claim: "code quality improvement",
      evidence: "",
    },
    {
      _id: "11",
      title: "Test-Driven Development as a Defect-Reduction Practice.",
      authors: "Williams, L., Maximilien, E. M. & Vouk, M.",
      source: "4th International Symposium on Software Reliability Engineering, 2003. ISSRE 2003, 34–45.",
      pubyear: "2001",
      doi: "https://doi.org/10.1109/issre.2003.1251029",
      claim: "product quality improvement",
      evidence: "strong against",
    },
    {
      _id: "12",
      title: "An Empirical Study of Test-Driven Development vs. Test-Last Development Using Eye Tracking.",
      authors: "Choma, J., Guerra, E. M., Silva, T. S. da, Albuquerque, T., Albuquerque, V. G. & Zaina, L. M.",
      source: "WBMA, 1106(1), 11–24.",
      pubyear: "2019",
      doi: "https://doi.org/10.1007/978-3-030-36701-5_2",
      claim: "code quality improvement",
      evidence: "weak against",
    },
    {
      _id: "13",
      title: "Do COMSCI Stundent Dream Of Digital Sheeps? A",
      authors: "I. M. I. Up",
      source: "AUT SLUMS",
      pubyear: "2000",
      doi: "N/A",
      claim: "?",
      evidence: "?",
    },
    {
      _id: "14",
      title: "Do COMSCI Stundent Dream Of Digital Sheeps? B",
      authors: "I. M. I. Up",
      source: "AUT SCUMS",
      pubyear: "2001",
      doi: "N/A",
      claim: "?",
      evidence: "?",
    },
    {
      _id: "15",
      title: "Do COMSCI Stundent Dream Of Digital Sheeps? C",
      authors: "I. M. I. Up",
      source: "AUT SUMS",
      pubyear: "2002",
      doi: "N/A",
      claim: "?",
      evidence: "?",
    },
];
  
export default data;
  